[functions]
  directory = "netlify/functions"

[plugins]
  [[plugins.inputs]]
  # Array of user-agent names to prerender
  # (we recommend leaving this as is)
  userAgents = [
    "googlebot",
    "yahoo-slurp",
    "bingbot",
    "duckduckbot",
    "baiduspider",
    "yandex",
  ]
